"""Frontière structurelle partagée par le module codeview et son double mémoire."""

from pathlib import Path
from typing import Protocol, runtime_checkable

from .codeview import PathClass, Symbol


@runtime_checkable
class CodeView(Protocol):
    def symbols(self, path: Path) -> list[Symbol]: ...
    def module_defs(self, path: Path) -> list[str]: ...
    def snippet(self, path: Path, start: int, end: int) -> str: ...
    def is_binary(self, path: Path) -> bool: ...
    def classify_repo_path(self, path: Path) -> PathClass: ...
    def is_path_within(self, child: Path, parent: Path) -> bool: ...
